version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/BE
    overwrite: yes
permissions:
  - object: /
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  AfterInstall:
    # location은 프로젝트의 root경로를 기준
    # 파일을 올린 후 진행해야하는 작업을 적은 deploy.sh 파일 경로를 적어줍니다.
    # 필요 없을 경우 안 적어도 되는 것 같습니다(테스트 필요).
    - location: scripts/deploy.sh
      timeout: 300
      runas: ec2-user
